server.servlet.context-path=/api/v1

# Postgres
spring.data.jdbc.dialect=org.hibernate.dialect.PostgreSQLDialect

# MySQL
#spring.data.jdbc.dialect=org.hibernate.dialect.MySQL8Dialect

# Best practice
spring.jpa.open-in-view=false
spring.datasource.hikari.auto-commit=false