server.servlet.context-path=/api/v1
server.port=8081

# MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Best practice
spring.jpa.open-in-view=false
spring.datasource.hikari.auto-commit=false